

export const GET_POKEMONS='GET_POKEMONS'


export const SEARCH_POKEMON_REQUEST = 'SEARCH_POKEMON_REQUEST' 
export const SEARCH_POKEMON = 'SEARCH_POKEMON' 
export const SEARCH_POKEMON_ERROR = 'SEARCH_POKEMON_ERROR' 

export const FILTER_POKEMON='FILTER_POKEMON' 

export const CLEAR_FILTER='CLEAR_FILTER' 